swagger: "2.0"
info:
  description: Swagger - Phase 2 - Transaction
  version: 1.0.0
  title: "ArgentBank : API documentation for transaction"
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - https
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponseUser'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponseUser'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponseUser'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/{userId}/transactions/{month}/{year}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: An identified user can see all his transactions for the current month.
      description: >-
        API for fetching the transactions in the current month for an identified
        user
      operationId: readAllTransaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true 
        - in: path
          name: userId
          required: true
          type: integer
          description: user unique Id
        - in: path
          name: month
          required: true
          type: integer
          description: month format integer
        - in: path
          name: year
          required: true
          type: integer
          description: year 
      responses:
        "200":
          description: Successfully get user's all transactions for the current month
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/{userId}/transactions/:
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Add a new transaction information for an identified user.
      description: API for adding a new transaction information for an identified user
      operationId: createTransaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: userId
          required: true
          type: integer
          description: user unique Id
        - in: body
          name: body
          description: Created transaction object
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        "200":
          description: Successfully created a transaction!
          schema:
            $ref: "#/definitions/ApiResponseTransaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/{userId}/transactions/{transactionId}:
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Edit a specific transaction information for un identified user.
      description: API for updating an existent transaction
      operationId: updateTransaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: userId
          required: true
          type: integer
          description: user unique Id
        - in: path
          name: transactionId
          required: true
          type: integer
          description: Transaction unique id
        - in: body
          name: body
          description: Updated transaction object
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        "200":
          description: Successfully updated an user's specific transaction!
          schema:
            $ref: "#/definitions/ApiResponseTransaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Deletes a specific transaction information for un identified user.
      description: API for deleting an existent transaction
      operationId: deleteTransaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: userId
          required: true
          type: integer
          description: user unique Id
        - in: path
          name: transactionId
          required: true
          type: integer
          description: Transaction unique id
      responses:
        "200":
          description: Successfully delete an existent transaction!
          schema:
            $ref: "#/definitions/ApiResponse"  
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponseUser:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  ApiResponse: 
    type: object
    properties:
      status:
        type: integer
        example: 200
      message:
        type: string
        example: success
  ApiResponseTransaction:
    type: object
    properties:
      status:
        type: integer
        example: 200
      message:
        type: string
        example: success
      transaction:
        type: object
        properties: 
          id:
            type: string
            format: int64
            description: User id
            example: 20
          date:
            type: string
            format: date-time
            example: 2022-02-16T09:12:32.766Z
          description:
            type: string
            example: Argent Bank notification
          amount:
            type: integer
            example: 200
          balance:
            type: integer
            example: 5000
          type:
            type: string
            example: Electricity
          category:
            type: string
            example: Household
          notes:
            type: string
            example: Electricity bill for July 2022
  Transactions:
    type: array
    items: 
      $ref: '#/definitions/Transaction'
  Transaction:
    type: object
    properties:
      date:
        type: string
        format: date-time
        example: 2022-02-16T09:12:32.766Z
      description:
        type: string
        example: Argent Bank notification
      amount:
        type: integer
        example: 200
      balance:
        type: integer
        example: 5000
      type:
        type: string
        example: Electricity
      category:
        type: string
        example: Household
      notes:
        type: string
        example: Electricity bill for July 2022